#!/bin/sh

DIR=$(dirname $0)

echo 'DROP DATABASE IF EXISTS yii2_gii_plus_tests;
CREATE DATABASE yii2_gii_plus_tests;' | mysql

$DIR/yii migrate --interactive=0
$DIR/yii gii/base_model --enableI18N=1 --interactive=0
$DIR/yii gii/custom_model --interactive=0
$DIR/yii gii/base_model --enableI18N=1 --interactive=0 --overwrite=1
$DIR/yii gii/base_model --enableI18N=1 --interactive=0 --overwrite=1
