#!/bin/sh
set -e

DIR=$(dirname $0)

echo 'CREATE DATABASE yii2_gii_plus_tests;' | mysql

$DIR/yii migrate/up --interactive=0
$DIR/yii gii/basemodel --interactive=0 --overwrite=1
$DIR/yii gii/usermodel --interactive=0 --overwrite=1
$DIR/yii gii/basemodel --interactive=0 --overwrite=1
$DIR/yii gii/basemodel --interactive=0 --overwrite=1
$DIR/yii migrate/down --interactive=0

echo 'DROP DATABASE yii2_gii_plus_tests;' | mysql
