#!/bin/sh

DIR=$(dirname $0)

EXPECTED1="Running 'Base Model Generator'...

The following files will be generated:
  [unchanged] models/base/BlogBase.php
  [unchanged] models/query/base/BlogQueryBase.php
  [unchanged] models/base/CommentBase.php
  [unchanged] models/query/base/CommentQueryBase.php
  [unchanged] models/base/PostBase.php
  [unchanged] models/query/base/PostQueryBase.php

No files were chosen to be generated."
ACTUAL1=`$DIR/yii gii/base_model --interactive=0 --overwrite=0`

if [ "$EXPECTED1" = "$ACTUAL1" ]; then
    echo '1 passed'
else
    echo $ACTUAL1
    exit 1
fi

EXPECTED2="Running 'Custom Model Generator'...

The following files will be generated:
  [unchanged] models/Blog.php
  [unchanged] models/query/BlogQuery.php
  [unchanged] models/Comment.php
  [unchanged] models/query/CommentQuery.php
  [unchanged] models/Post.php
  [unchanged] models/query/PostQuery.php

No files were chosen to be generated."
ACTUAL2=`$DIR/yii gii/custom_model --interactive=0 --overwrite=0`

if [ "$EXPECTED2" = "$ACTUAL2" ]; then
    echo '2 passed'
else
    echo $ACTUAL2
    exit 2
fi
